### ISSUE TITLE
could you please upload your large V3 model on google drive or dropbox??

### ISSUE THREAD

**Issue by dedoogong** [THUKey/pytorch-mobilenet-v3#10]
I'm trying to train mobilenetV3 on DGX 1 using imagenet 2012 dataset but I found it's quite hard to reach to the reported accuracy. 

I just got Acc-1 : 70.xx %

Humm.... can I ask you to send me or upload your mobilenetV3-large model on google drive/dropbox? 

Thank you!

**Comment by cxxgtxy** [comment]
@kuan-wang @dedoogong 
I find three models which are bettter than V3, please refer to https://github.com/xiaomi-automl/MoGA

**Comment by dedoogong** [comment]
Thank you!
