### ISSUE TITLE
pretrained mobilenetv3_small_67.4.pth.tar file is broken

### ISSUE THREAD

**Issue by luojiapeng14** [THUKey/pytorch-mobilenet-v3#14]
RT. cannot open this file as a .tar file

**Comment by jungin500** [comment]
I was able to open the file as ".pth" file, not as the archived tar. you could rename it from `mobilenetv3_small_67.4.pth.tar` to `mobilenetv3_small_67.4.pth`, and load it with `torch.load` or tools like [Netron](https://github.com/lutzroeder/netron) - which is a great model visualizer - would  be a good method to inspect models.
